apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: true
  artifacts:
    - image: ferennag/webui
      context: webui
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.tsx'
            dest: .
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/**/*.css'
            dest: .
    - image: ferennag/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: ferennag/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: ferennag/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: ferennag/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: ferennag/eventbus
      context: eventbus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
